<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-BPQK2HC0" name="test.java.com.smoketest.RingCSVAddToCart" tests="1" failures="0" timestamp="24 Nov 2015 12:01:50 GMT" time="0.068" errors="1">
  <testcase name="testCSVData" time="0.068" classname="test.java.com.smoketest.RingCSVAddToCart">
    <error type="org.testng.TestNGException" message="
The data provider is trying to pass 1 parameters but the method test.java.com.smoketest.RingCSVAddToCart#testCSVData takes 3 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 1 parameters but the method test.java.com.smoketest.RingCSVAddToCart#testCSVData takes 3 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1249)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1118)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1245)
	... 13 more
]]>
    </error>
  </testcase> <!-- testCSVData -->
</testsuite> <!-- test.java.com.smoketest.RingCSVAddToCart -->
